"""init session and session_event

Revision ID: 00cdbd72e6d8
Revises: 
Create Date: 2026-07-16 11:09:00.711844
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '00cdbd72e6d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('external_user', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('effective_context_window', sa.Integer(), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('head_event_id', sa.UUID(), nullable=True),
    sa.Column('last_boundary_id', sa.UUID(), nullable=True),
    sa.Column('active_compaction', sa.String(length=32), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('logical_parent_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_call_id', sa.Text(), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('finish_reason', sa.Text(), nullable=True),
    sa.Column('is_sidechain', sa.Boolean(), nullable=False),
    sa.Column('agent_id_ref', sa.Text(), nullable=True),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['logical_parent_id'], ['session_event.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['session_event.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_message', 'session_event', ['session_id', 'message_id'], unique=False)
    op.create_index('ix_event_parent', 'session_event', ['parent_id'], unique=False)
    op.create_index('ix_event_session', 'session_event', ['session_id', 'seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_session', table_name='session_event')
    op.drop_index('ix_event_parent', table_name='session_event')
    op.drop_index('ix_event_message', table_name='session_event')
    op.drop_table('session_event')
    op.drop_table('session')
    # ### end Alembic commands ###
